import './armario.model';
import './audit-log.model';
import './contract-portfolio.model';
import './categorias-armario.model';
import './categorias-gaveta.model';
import './estoque-insumo.model';
import './estoque-medicamento.model';
import './gaveta.model';
import './insumo.model';
import './login.model';
import './login-log.model';
import './medicamento.model';
import './movimentacao.model';
import './notificacao.model';
import './residente.model';
import './system-config.model';
import './tenant.model';
import './tenant-config.model';

export { setupAssociations } from './associations.models';
